### PR TITLE
Fix upload api

### PR DESCRIPTION
**Pull request by etiennea**

### CODE REVIEW

**Comment by miki2826** [comment]
Hi,
Botly supports multiple pages, that is why you need to pass the page id. 

Is it not working for you?

**Comment by etiennea** [comment]
Aaa ok no it was not working out of the box, getting an very vage opengraph error.

Also how do you the send one of these attachements?

Thanks in advance!

**Comment by miki2826** [comment]
very similar to the send API - this is for uploading content for a later use:
https://developers.facebook.com/docs/messenger-platform/send-api-reference/attachment-upload

**Comment by etiennea** [comment]
I get why to have this API but I don't understand how to then use that attachement?

**Pull request closed without merging**
